version: '3.7'

services:
  multishop-api:
    container_name: multishop-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/home/node/app/src
      - ./tmp/:/home/node/app/tmp
      - ./node_modules/:/home/node/app/node_modules
      - ./mailTemplates/:/home/node/app/mailTemplates
      - ./package.json:/home/node/app/package.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./jest.config.js:/home/node/app/jest.config.js
      - ./jest.setup.ts:/home/node/app/jest.setup.ts
      - ./ormconfig.js:/home/node/app/ormconfig.js
      - ./.env:/home/node/app/.env
    expose:
      - '3333'
    ports:
      - '3333:3333'
    networks:
      - multishop-network
    command: yarn watch
    depends_on:
      - multishop-redis
      - multishop-postgresql
      - multishop-bitcoincore

  multishop-redis:
    container_name: multishop-redis
    image: redis:alpine
    networks:
      - multishop-network

  multishop-postgresql:
    container_name: multishop-postgresql
    image: docker.io/bitnami/postgresql:latest
    volumes:
      - 'phoenix_postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=phoenix
    networks:
      - multishop-network

  multishop-pgadmin:
    container_name:  multishop-pgadmin
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5051:80"
    depends_on:
      - multishop-postgresql
    networks:
      - multishop-network

  multishop-bitcoincore:
    container_name: multishop-bitcoincore
    image: ruimarinho/bitcoin-core:0.17
    volumes:
      - 'phoenix_bitcoin-core_data:/home/bitcoin/.bitcoin'
    command:
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcauth=btc:1434f33099c1f7358f5efeb11078bd8a$$f8fefbaeefbd3af8a8da00c9df43035971da00a9de30a80ce5af3c748b6b4d84
      -prune=600
      -wallet=phoenix
      -wallet=miner
      -walletnotify='sh /home/bitcoin/.bitcoin/walletnotify.sh %s'
      -blocknotify='sh /home/bitcoin/.bitcoin/blocknotify.sh %s'
    networks:
      - multishop-network

networks:
  multishop-network:

volumes:
  phoenix_postgresql_data:
  phoenix_bitcoin-core_data:
