# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name:  Install dependencies
        run: yarn

      - name: Run Build
        run: yarn build

      - name: Copy dist to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key:  ${{ secrets.SSH_KEY }}
          source: "dist,package.json,mailTemplates"
          target: "app/backend"

      - name: Run server comands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key:  ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/backend
            npm install --only-prod
            ./node_modules/.bin/typeorm migration:run
            docker-compose down
            docker-compose up -d
            # pm2 restart server
